spring:
  application:
    name: prescription-service

  datasource:
    url: jdbc:postgresql://localhost:5432/prescription_db
    username: user
    password: pass

  jpa:
    hibernate:
      # Отключаем автогенерацию таблиц от Hibernate
      ddl-auto: validate

  flyway:
    # Включаем инструмент миграций Flyway
    enabled: true
    # Позволяет начать миграции, даже если в базе уже есть какие-то таблицы
    baseline-on-migrate: true

server:
  port: 8081

grpc:
  server:
    port: 9090